"""
Django base settings for Catechism 2025-2026 project.
Generated by 'django-admin startproject' using Django 6.0.6, then customized.

WHY SPLIT SETTINGS?
───────────────────
Django generates a single settings.py. We split it into:
  - base.py     → shared config (this file)
  - development.py → DEBUG=True, debug toolbar, console email
  - production.py  → DEBUG=False, real email, security hardening

manage.py points to development.py, wsgi/asgi point to production.py.
Each env file does `from .base import *` to inherit everything here.
"""

from pathlib import Path

from decouple import config, Csv

# ──────────────────────────────────────────────
# PATHS
# ──────────────────────────────────────────────
# BASE_DIR = school_admin/ (the project root containing manage.py)
# Since settings moved into config/settings/, we go up 3 levels:
#   base.py → settings/ → config/ → school_admin/
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# ──────────────────────────────────────────────
# SECURITY
# ──────────────────────────────────────────────
# python-decouple reads from .env file so secrets stay out of code
SECRET_KEY = config("SECRET_KEY", default="django-insecure-change-me-in-production")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# ──────────────────────────────────────────────
# INSTALLED APPS
# ──────────────────────────────────────────────
# WHY separate lists? Makes it easy to see what's Django built-in,
# what's third-party, and what's our own code.

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",      # For template filters like |intcomma
]

THIRD_PARTY_APPS = [
    "django_htmx",                  # HTMX middleware + request helpers
]

# WHY this order? 'common' first (shared base models), then 'accounts'
# (custom User model), then feature apps.
LOCAL_APPS = [
    "common",
    "accounts",
    "students",
    "admissions",
    "imports",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


# ──────────────────────────────────────────────
# MIDDLEWARE
# ──────────────────────────────────────────────
# Order matters! Security first, then session, then auth, etc.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",          # Adds request.htmx
]

ROOT_URLCONF = "config.urls"


# ──────────────────────────────────────────────
# TEMPLATES
# ──────────────────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # WHY "DIRS"? This tells Django to look in our global templates/
        # folder (for base.html, nav, error pages, etc.) in addition to
        # each app's own templates/ folder (handled by APP_DIRS=True).
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Our custom context processor — adds global vars to every template
                "common.context_processors.global_context",
                "common.context_processors.notifications_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ──────────────────────────────────────────────
# DATABASE
# ──────────────────────────────────────────────
# WHY PostgreSQL? The spec requires it. We read credentials from .env
# so they never get committed to git. We also support DATABASE_URL
# using dj-database-url.
import dj_database_url

DATABASE_URL = config("DATABASE_URL", default="")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL)
    }
    # Ensure ENGINE is explicitly set to postgresql
    DATABASES["default"]["ENGINE"] = "django.db.backends.postgresql"
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DATABASE_NAME", default="school_admin_db"),
            "USER": config("DATABASE_USER", default="postgres"),
            "PASSWORD": config("DATABASE_PASSWORD", default=""),
            "HOST": config("DATABASE_HOST", default="localhost"),
            "PORT": config("DATABASE_PORT", default="5432"),
        }
    }




# ──────────────────────────────────────────────
# CUSTOM USER MODEL
# ──────────────────────────────────────────────
# WHY custom User? We need email-based login and a 'role' field.
# MUST be set BEFORE the first migration runs.
AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/accounts/login/"


# ──────────────────────────────────────────────
# PASSWORD VALIDATION
# ──────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ──────────────────────────────────────────────
# INTERNATIONALIZATION
# ──────────────────────────────────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"      # Indian school → IST
USE_I18N = True
USE_TZ = True


# ──────────────────────────────────────────────
# STATIC & MEDIA FILES
# ──────────────────────────────────────────────
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]    # Our custom static files
STATIC_ROOT = BASE_DIR / "staticfiles"      # collectstatic output

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"             # User uploads (Excel files)


# ──────────────────────────────────────────────
# DEFAULTS
# ──────────────────────────────────────────────
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Our app-level constant for pagination
DEFAULT_PAGE_SIZE = 25
