# Generated by Django 6.0.6 on 2026-06-11 10:37

import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_name", models.CharField(max_length=200)),
                (
                    "student_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated: STU-YYYY-NNNN",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        validators=[common.validators.validate_not_future_date]
                    ),
                ),
                ("residential_address", models.TextField(blank=True, default="")),
                (
                    "attended_catechism",
                    models.BooleanField(
                        default=False, verbose_name="Attended Catechism?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="admissions.division",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="admissions.schoolclass",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked user account for student login. Can be blank.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "father_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[common.validators.validate_phone_number],
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "mother_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[common.validators.validate_phone_number],
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_info",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Information",
                "verbose_name_plural": "Parent Information",
            },
        ),
        migrations.CreateModel(
            name="CatechismInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catechism_teacher_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Catechism Teacher Name",
                    ),
                ),
                (
                    "provision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catechism_students",
                        to="admissions.provision",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catechism_students",
                        to="admissions.unit",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catechism_info",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catechism Information",
                "verbose_name_plural": "Catechism Information",
            },
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["student_name"], name="students_st_student_10bb5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["student_number"], name="students_st_student_e212ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["email"], name="students_st_email_71b1de_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["status"], name="students_st_status_6012f4_idx"),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["school_class"], name="students_st_school__f62b46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["division"], name="students_st_divisio_ba652b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentinfo",
            index=models.Index(
                fields=["father_name"], name="students_pa_father__976e17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentinfo",
            index=models.Index(
                fields=["mother_name"], name="students_pa_mother__501314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentinfo",
            index=models.Index(
                fields=["father_phone"], name="students_pa_father__30682f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentinfo",
            index=models.Index(
                fields=["mother_phone"], name="students_pa_mother__47d111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catechisminfo",
            index=models.Index(
                fields=["catechism_teacher_name"], name="students_ca_catechi_30ce3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catechisminfo",
            index=models.Index(
                fields=["provision"], name="students_ca_provisi_333c43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catechisminfo",
            index=models.Index(fields=["unit"], name="students_ca_unit_id_22e2b2_idx"),
        ),
    ]
