# Generated by Django 6.0.6 on 2026-06-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_occupation"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentinfo",
            name="father_occupation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fathers",
                to="admissions.occupation",
            ),
        ),
        migrations.AlterField(
            model_name="parentinfo",
            name="mother_occupation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mothers",
                to="admissions.occupation",
            ),
        ),
    ]
